version: '3'
services:
  # RPC daemons
  bitcoin:
    image: vulpemventures/bitcoin:latest
    networks:
      local:
        ipv4_address: 10.10.0.10
    ports:
      - 18443:19001
      - 18442:19000
    volumes:
      - ./config/:/config
    restart: unless-stopped
  liquid:
    image: vulpemventures/liquid:latest
    networks:
      local:
        ipv4_address: 10.10.0.11
    ports:
      - 7041:18884
      - 7040:18886
    volumes:
      - ./liquid-config/:/config
    restart: unless-stopped
  # Block explorer REST servers
  electrs:
    image: vulpemventures/electrs:latest
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - 10.10.0.10:19001
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    networks:
      local:
        ipv4_address: 10.10.0.12
    links:
      - bitcoin
    depends_on:
      - bitcoin
    ports:
      - 51401:60401
      - 3002:3002
    volumes:
      - ./config/:/config
    restart: unless-stopped
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - 10.10.0.11:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    networks:
      local:
        ipv4_address: 10.10.0.13
    links:
      - liquid
    depends_on:
      - liquid
    ports:
      - 60401:60401
      - 3012:3002
    volumes:
      - ./liquid-config/:/config
    restart: unless-stopped
  # Chopsticks
  chopsticks:
    image: vulpemventures/nigiri-chopsticks:latest
    command:
      - --use-faucet
      - --use-mining
      - --use-logger
      - --rpc-addr
      - 10.10.0.10:19001
      - --electrs-addr
      - 10.10.0.12:3002
      - --addr
      - 0.0.0.0:3000
    links:
      - electrs
      - bitcoin
    depends_on:
      - electrs
    ports:
      - 3000:3000
    networks:
      local:
        ipv4_address: 10.10.0.16
    restart: unless-stopped
  chopsticks-liquid:
    image: vulpemventures/nigiri-chopsticks:latest
    command:
      - --use-faucet
      - --use-mining
      - --use-logger
      - --rpc-addr
      - 10.10.0.11:18884
      - --electrs-addr
      - 10.10.0.13:3002
      - --addr
      - 0.0.0.0:3000
      - --chain
      - liquid
    links:
      - electrs-liquid
      - liquid
    depends_on:
      - electrs-liquid
    ports:
      - 3001:3000
    networks:
      local:
        ipv4_address: 10.10.0.17
    restart: unless-stopped

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
